"use client";

import { useState } from "react";
import { X, Download, BookOpen, Loader2 } from "lucide-react";
import type { StoryReport } from "@/src/lib/llm/anthropic";

interface Props {
  report: StoryReport;
  threadTitle: string;
  onClose: () => void;
}

// ---------------------------------------------------------------------------
// PDF helpers
// ---------------------------------------------------------------------------

function escHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function buildPrintHTML(report: StoryReport, date: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${escHtml(report.title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      color: #1C1A16;
      padding: 56px 72px;
      max-width: 860px;
      margin: 0 auto;
    }
    .brand {
      font-size: 10px; font-weight: 700; letter-spacing: 0.12em;
      text-transform: uppercase; color: #2891DA; margin-bottom: 14px;
    }
    h1 { font-size: 26px; font-weight: 800; line-height: 1.25; margin-bottom: 6px; }
    .meta { font-size: 11px; color: #6B7280; padding-bottom: 24px; border-bottom: 3px solid #2891DA; margin-bottom: 32px; }
    h2 {
      font-size: 15px; font-weight: 700; color: #1C1A16;
      margin-top: 28px; margin-bottom: 10px;
    }
    p { font-size: 11.5px; line-height: 1.85; color: #374151; margin-bottom: 9px; }
    ul.findings { list-style: none; padding: 0; margin-bottom: 4px; }
    ul.findings li { display: flex; align-items: flex-start; gap: 10px; margin-bottom: 8px; }
    ul.findings li .num {
      background: #2891DA; color: #fff; border-radius: 50%;
      width: 18px; height: 18px; display: flex; align-items: center;
      justify-content: center; font-size: 9px; font-weight: 700;
      flex-shrink: 0; margin-top: 2px;
    }
    ul.findings li .text { font-size: 11.5px; color: #374151; line-height: 1.7; }
    .recs {
      background: rgba(40,145,218,0.05);
      border: 1px solid rgba(40,145,218,0.22);
      border-radius: 8px; padding: 20px 24px; margin-top: 28px;
    }
    .recs h2 { margin-top: 0; }
    .recs ul { list-style: none; padding: 0; }
    .recs li {
      display: flex; gap: 10px; margin-bottom: 9px;
      font-size: 11.5px; color: #374151; line-height: 1.7;
    }
    .recs li::before { content: "→"; color: #2891DA; font-weight: 700; flex-shrink: 0; }
    .agents { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 10px; }
    .badge {
      background: #F3F4F6; border: 1px solid #E5E7EB;
      border-radius: 999px; padding: 3px 10px; font-size: 10px; color: #6B7280;
    }
    .footer {
      margin-top: 48px; padding-top: 14px; border-top: 1px solid #E5E7EB;
      display: flex; justify-content: space-between; font-size: 10px; color: #9CA3AF;
    }
    @page { margin: 0; }
  </style>
</head>
<body>
  <div class="brand">SRIntelligence · Executive Report</div>
  <h1>${escHtml(report.title)}</h1>
  <div class="meta">${escHtml(date)}</div>

  <h2>Executive Summary</h2>
  ${report.executiveSummary.split(/\n{2,}/).map((p) => `<p>${escHtml(p)}</p>`).join("")}

  <h2>Key Findings</h2>
  <ul class="findings">
    ${report.keyFindings
      .map(
        (f, i) =>
          `<li><div class="num">${i + 1}</div><div class="text">${escHtml(f)}</div></li>`,
      )
      .join("")}
  </ul>

  ${report.sections
    .map(
      (s) => `
  <h2>${escHtml(s.heading)}</h2>
  ${s.body.split(/\n{2,}/).map((p) => `<p>${escHtml(p)}</p>`).join("")}
  `,
    )
    .join("")}

  <div class="recs">
    <h2>Recommendations</h2>
    <ul>${report.recommendations.map((r) => `<li>${escHtml(r)}</li>`).join("")}</ul>
  </div>

  <h2>Methodology</h2>
  <p>${escHtml(report.methodology)}</p>
  ${
    report.agentsUsed.length > 0
      ? `<div class="agents">${report.agentsUsed.map((a) => `<span class="badge">${escHtml(a)}</span>`).join("")}</div>`
      : ""
  }

  <div class="footer">
    <span>Generated by SRIntelligence™</span>
    <span>${escHtml(date)}</span>
  </div>
  <script>window.onload = function() { window.print(); };</script>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// PPTX helpers
// ---------------------------------------------------------------------------

const SRI_BLUE  = "2891DA";
const SRI_DARK  = "1C1A16";
const SRI_LIGHT = "F7F8FA";

async function exportToPptx(report: StoryReport, date: string) {
  const pptxgen = (await import("pptxgenjs")).default;
  const prs = new pptxgen();
  prs.layout = "LAYOUT_WIDE"; // 13.33 × 7.5 inches

  const addHeader = (slide: ReturnType<typeof prs.addSlide>, title: string) => {
    slide.addShape(prs.ShapeType.rect, {
      x: 0, y: 0, w: "100%", h: 0.62,
      fill: { color: SRI_BLUE },
      line: { color: SRI_BLUE, width: 0 },
    });
    slide.addText(title, {
      x: 0.45, y: 0.1, w: 12.4, h: 0.42,
      fontSize: 17, bold: true, color: "FFFFFF",
    });
  };

  // ── Slide 1: Title ───────────────────────────────────────────────────────
  const s1 = prs.addSlide();
  s1.background = { color: SRI_DARK };

  s1.addText("SRIntelligence™", {
    x: 0.5, y: 0.45, w: 12, h: 0.35,
    fontSize: 11, bold: true, color: SRI_BLUE, charSpacing: 2,
  });
  s1.addShape(prs.ShapeType.rect, {
    x: 0.5, y: 0.9, w: 1.2, h: 0.06,
    fill: { color: SRI_BLUE }, line: { color: SRI_BLUE, width: 0 },
  });
  s1.addText(report.title, {
    x: 0.5, y: 1.15, w: 11.5, h: 3.2,
    fontSize: 30, bold: true, color: "FFFFFF", valign: "top", wrap: true,
  });
  s1.addText("Executive Report", {
    x: 0.5, y: 4.5, w: 12, h: 0.4,
    fontSize: 14, color: "999999",
  });
  s1.addText(date, {
    x: 0.5, y: 7.1, w: 12, h: 0.3,
    fontSize: 9, color: "555555",
  });

  // ── Slide 2: Executive Summary ───────────────────────────────────────────
  const s2 = prs.addSlide();
  s2.background = { color: "FFFFFF" };
  addHeader(s2, "Executive Summary");
  s2.addText(report.executiveSummary, {
    x: 0.45, y: 0.82, w: 12.4, h: 6.3,
    fontSize: 11, color: SRI_DARK, valign: "top", wrap: true, paraSpaceAfter: 8,
  });

  // ── Slide 3: Key Findings ────────────────────────────────────────────────
  const s3 = prs.addSlide();
  s3.background = { color: "FFFFFF" };
  addHeader(s3, "Key Findings");
  report.keyFindings.forEach((finding, i) => {
    const y = 0.88 + i * 0.72;
    if (y > 7.0) return; // guard overflow
    s3.addShape(prs.ShapeType.ellipse, {
      x: 0.45, y: y + 0.02, w: 0.28, h: 0.28,
      fill: { color: SRI_BLUE }, line: { color: SRI_BLUE, width: 0 },
    });
    s3.addText(String(i + 1), {
      x: 0.45, y: y + 0.02, w: 0.28, h: 0.28,
      fontSize: 9, bold: true, color: "FFFFFF", align: "center", valign: "middle",
    });
    s3.addText(finding, {
      x: 0.85, y, w: 12.0, h: 0.62,
      fontSize: 11, color: SRI_DARK, valign: "middle", wrap: true,
    });
  });

  // ── Slides for each analysis section ────────────────────────────────────
  for (const section of report.sections) {
    const sN = prs.addSlide();
    sN.background = { color: "FFFFFF" };
    addHeader(sN, section.heading);
    sN.addText(section.body, {
      x: 0.45, y: 0.82, w: 12.4, h: 6.3,
      fontSize: 11, color: SRI_DARK, valign: "top", wrap: true, paraSpaceAfter: 8,
    });
  }

  // ── Recommendations slide ────────────────────────────────────────────────
  const sR = prs.addSlide();
  sR.background = { color: SRI_LIGHT };
  addHeader(sR, "Recommendations");
  report.recommendations.forEach((rec, i) => {
    const y = 0.88 + i * 1.02;
    if (y > 7.0) return;
    sR.addShape(prs.ShapeType.rect, {
      x: 0.45, y, w: 12.4, h: 0.86,
      fill: { color: "FFFFFF" },
      line: { color: SRI_BLUE, width: 1.5, dashType: "solid" },
      rectRadius: 4,
    });
    sR.addText(`${i + 1}.`, {
      x: 0.6, y: y + 0.06, w: 0.35, h: 0.72,
      fontSize: 13, bold: true, color: SRI_BLUE, valign: "middle",
    });
    sR.addText(rec, {
      x: 0.98, y: y + 0.06, w: 11.7, h: 0.72,
      fontSize: 11, color: SRI_DARK, valign: "middle", wrap: true,
    });
  });

  // ── Methodology slide ────────────────────────────────────────────────────
  const sM = prs.addSlide();
  sM.background = { color: "FFFFFF" };
  addHeader(sM, "Methodology & Agents");
  sM.addText(report.methodology, {
    x: 0.45, y: 0.82, w: 12.4, h: 4.5,
    fontSize: 11, color: SRI_DARK, valign: "top", wrap: true,
  });
  if (report.agentsUsed.length > 0) {
    sM.addText("Agents Used", {
      x: 0.45, y: 5.5, w: 12, h: 0.35,
      fontSize: 10, bold: true, color: "888888",
    });
    sM.addText(report.agentsUsed.join("  ·  "), {
      x: 0.45, y: 5.85, w: 12, h: 0.45,
      fontSize: 10, color: "555555",
    });
  }
  sM.addText(`Generated by SRIntelligence™  ·  ${date}`, {
    x: 0.45, y: 7.15, w: 12, h: 0.25,
    fontSize: 9, color: "AAAAAA",
  });

  const safeTitle = report.title.replace(/[^a-z0-9\s-]/gi, "").trim().replace(/\s+/g, "_");
  await prs.writeFile({ fileName: `${safeTitle}_Executive_Report.pptx` });
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function StoryReportModal({ report, onClose }: Props) {
  const [exportingPptx, setExportingPptx] = useState(false);

  const generatedDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const handleExportPDF = () => {
    const win = window.open("", "_blank");
    if (!win) { alert("Allow pop-ups to export PDF."); return; }
    win.document.write(buildPrintHTML(report, generatedDate));
    win.document.close();
  };

  const handleExportPptx = async () => {
    setExportingPptx(true);
    try {
      await exportToPptx(report, generatedDate);
    } catch (err) {
      console.error("PPTX export failed:", err);
      alert("PowerPoint export failed — please try PDF instead.");
    } finally {
      setExportingPptx(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/60" onClick={onClose} />

      {/* Modal panel */}
      <div
        className="relative z-10 flex flex-col rounded-2xl overflow-hidden shadow-2xl"
        style={{ width: "min(880px, 96vw)", height: "92vh", background: "#ffffff" }}
      >
        {/* ── Header bar ───────────────────────────────────────────────── */}
        <div
          className="flex items-center justify-between px-6 py-3.5 shrink-0"
          style={{ background: "#1C1A16", borderBottom: "1px solid rgba(255,255,255,0.08)" }}
        >
          <div className="flex items-center gap-3">
            {/* Brand icon */}
            <div
              className="flex items-center justify-center w-7 h-7 rounded-lg shrink-0"
              style={{ background: "linear-gradient(135deg, #2891DA 0%, #C8956A 100%)" }}
            >
              <BookOpen size={14} style={{ color: "white" }} />
            </div>
            <div>
              <p className="text-sm font-semibold" style={{ color: "white" }}>
                Executive Report
              </p>
              <p className="text-xs" style={{ color: "rgba(255,255,255,0.45)" }}>
                {generatedDate}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* PDF */}
            <button
              onClick={handleExportPDF}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-opacity hover:opacity-80"
              style={{
                background: "rgba(255,255,255,0.1)",
                color: "white",
                border: "1px solid rgba(255,255,255,0.18)",
              }}
            >
              <Download size={12} />
              Export PDF
            </button>

            {/* PPTX */}
            <button
              onClick={handleExportPptx}
              disabled={exportingPptx}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-opacity hover:opacity-85 disabled:opacity-50"
              style={{ background: "#2891DA", color: "white" }}
            >
              {exportingPptx ? (
                <><Loader2 size={12} className="animate-spin" />Building…</>
              ) : (
                <>
                  <svg width="12" height="12" viewBox="0 0 16 16" fill="none" style={{ flexShrink: 0 }}>
                    <rect x="1" y="1" width="14" height="14" rx="2" stroke="white" strokeWidth="1.5" />
                    <rect x="4" y="4" width="4" height="8" rx="1" fill="white" />
                    <rect x="10" y="4" width="2" height="2" rx="0.5" fill="white" />
                    <rect x="10" y="7" width="2" height="2" rx="0.5" fill="white" />
                    <rect x="10" y="10" width="2" height="2" rx="0.5" fill="white" />
                  </svg>
                  PowerPoint
                </>
              )}
            </button>

            {/* Close */}
            <button
              onClick={onClose}
              className="flex items-center justify-center w-8 h-8 rounded-lg transition-opacity hover:opacity-70"
              style={{ background: "rgba(255,255,255,0.08)", color: "rgba(255,255,255,0.7)" }}
            >
              <X size={15} />
            </button>
          </div>
        </div>

        {/* ── Scrollable report body ────────────────────────────────────── */}
        <div
          className="flex-1 overflow-y-auto px-12 py-10"
          style={{ background: "#fafafa" }}
        >
          {/* Report header */}
          <div className="mb-8 pb-6" style={{ borderBottom: "3px solid #2891DA" }}>
            <p
              className="text-xs font-bold tracking-widest uppercase mb-2"
              style={{ color: "#2891DA", letterSpacing: "0.1em" }}
            >
              SRIntelligence · Executive Report
            </p>
            <h1 className="text-3xl font-extrabold mb-2 leading-tight" style={{ color: "#1C1A16" }}>
              {report.title}
            </h1>
            <p className="text-sm" style={{ color: "#9CA3AF" }}>{generatedDate}</p>
          </div>

          {/* Executive Summary */}
          <Section title="Executive Summary">
            {report.executiveSummary.split(/\n{2,}/).map((p, i) => (
              <p key={i} className={`text-sm leading-relaxed ${i > 0 ? "mt-3" : ""}`} style={{ color: "#374151" }}>
                {p}
              </p>
            ))}
          </Section>

          {/* Key Findings */}
          <Section title="Key Findings">
            <ul className="flex flex-col gap-2.5">
              {report.keyFindings.map((finding, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span
                    className="flex items-center justify-center text-xs font-bold shrink-0 rounded-full mt-0.5"
                    style={{ width: 20, height: 20, background: "#2891DA", color: "white" }}
                  >
                    {i + 1}
                  </span>
                  <span className="text-sm leading-relaxed" style={{ color: "#374151" }}>
                    {finding}
                  </span>
                </li>
              ))}
            </ul>
          </Section>

          {/* Analysis sections */}
          {report.sections.map((section, i) => (
            <Section key={i} title={section.heading}>
              {section.body.split(/\n{2,}/).map((p, j) => (
                <p key={j} className={`text-sm leading-relaxed ${j > 0 ? "mt-3" : ""}`} style={{ color: "#374151" }}>
                  {p}
                </p>
              ))}
            </Section>
          ))}

          {/* Recommendations */}
          <div
            className="mb-8 p-6 rounded-xl"
            style={{ background: "rgba(40,145,218,0.05)", border: "1px solid rgba(40,145,218,0.2)" }}
          >
            <h2 className="text-base font-bold mb-4" style={{ color: "#1C1A16" }}>
              Recommendations
            </h2>
            <ul className="flex flex-col gap-3">
              {report.recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="font-bold mt-0.5 shrink-0" style={{ color: "#2891DA", fontSize: 14 }}>
                    →
                  </span>
                  <span className="text-sm leading-relaxed" style={{ color: "#374151" }}>
                    {rec}
                  </span>
                </li>
              ))}
            </ul>
          </div>

          {/* Methodology */}
          <Section title="Methodology">
            <p className="text-sm leading-relaxed" style={{ color: "#374151" }}>
              {report.methodology}
            </p>
            {report.agentsUsed.length > 0 && (
              <div className="flex flex-wrap gap-2 mt-3">
                {report.agentsUsed.map((agent, i) => (
                  <span
                    key={i}
                    className="text-xs px-2.5 py-1 rounded-full"
                    style={{
                      background: "var(--bg-secondary)",
                      color: "var(--text-muted)",
                      border: "1px solid var(--border)",
                    }}
                  >
                    {agent}
                  </span>
                ))}
              </div>
            )}
          </Section>

          {/* Footer */}
          <div
            className="mt-8 pt-4 flex justify-between text-xs"
            style={{ borderTop: "1px solid var(--border)", color: "var(--text-muted)" }}
          >
            <span>Generated by SRIntelligence™</span>
            <span>{generatedDate}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Section helper
// ---------------------------------------------------------------------------

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-base font-bold mb-3" style={{ color: "#1C1A16" }}>
        {title}
      </h2>
      {children}
    </div>
  );
}
