-- Reports Module Schema
-- Database: CORTEX_TESTING
-- Schema: PUBLIC

-- Core documents table
CREATE TABLE IF NOT EXISTS PUBLIC.DOCUMENTS (
    DOCUMENT_ID VARCHAR(128) DEFAULT UUID_STRING() PRIMARY KEY,
    CONTENT_HASH VARCHAR(64) NOT NULL UNIQUE,
    FILE_NAME VARCHAR(512) NOT NULL,
    FILE_TYPE VARCHAR(32) NOT NULL, -- 'pdf' | 'docx' | 'pptx'
    FILE_SIZE_BYTES INTEGER NOT NULL,

    -- Text content & metadata
    FULL_TEXT TEXT,
    PAGES_COUNT INTEGER,

    -- Parsing metadata
    TEXT_DENSITY FLOAT,
    PARSING_METHOD VARCHAR(64), -- 'pdfmupdf' | 'claude_vision'

    -- Upload info
    UPLOAD_USER_ID VARCHAR(128) NOT NULL,
    UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INDEXED_AT TIMESTAMP_NTZ,

    -- Relevance ranking (mirrors news pattern)
    BASE_WEIGHT NUMBER(5,4) DEFAULT 1.0,
    DECAY_LAMBDA NUMBER(6,4) DEFAULT 0.05,
    FEEDBACK_SCORE NUMBER(8,4) DEFAULT 0,
    FEEDBACK_MULTIPLIER NUMBER(6,4) DEFAULT 1.0,

    -- Status tracking
    STATUS VARCHAR(32) DEFAULT 'pending' -- 'pending' | 'extracted' | 'indexed' | 'failed'
);

-- Document chunks with vector embeddings
CREATE TABLE IF NOT EXISTS PUBLIC.DOCUMENT_CHUNKS (
    CHUNK_ID VARCHAR(128) DEFAULT UUID_STRING() PRIMARY KEY,
    DOCUMENT_ID VARCHAR(128) NOT NULL,
    CHUNK_TEXT TEXT NOT NULL,
    CHUNK_INDEX INTEGER NOT NULL,

    -- Citation tracking (exact page numbers)
    PAGE_NUMBER INTEGER NOT NULL,
    PAGE_START_OFFSET INTEGER,
    PAGE_END_OFFSET INTEGER,
    SECTION_LABEL VARCHAR(256),

    -- Semantic metadata
    SEMANTIC_CHUNK_ID VARCHAR(128),
    CONTEXT_BEFORE VARCHAR(512),
    CONTEXT_AFTER VARCHAR(512),

    -- Embeddings (768-dimensional vector via Cortex)
    EMBEDDING VECTOR(768),
    EMBEDDING_MODEL VARCHAR(64),

    CHUNK_CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT FK_DOCUMENT_CHUNKS FOREIGN KEY (DOCUMENT_ID)
        REFERENCES PUBLIC.DOCUMENTS(DOCUMENT_ID)
);

-- Retrieval validation tracking (for query optimization feedback)
CREATE TABLE IF NOT EXISTS PUBLIC.RETRIEVAL_VALIDATIONS (
    VALIDATION_ID VARCHAR(128) DEFAULT UUID_STRING() PRIMARY KEY,
    QUERY_ID VARCHAR(128),
    DOCUMENT_ID VARCHAR(128),
    CYCLE_NUMBER INTEGER,
    RELEVANCE_SCORE NUMBER(3,2),
    COVERAGE_SCORE NUMBER(3,2),
    IS_VALID BOOLEAN,
    FEEDBACK TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Document feedback (user ratings for relevance ranking)
CREATE TABLE IF NOT EXISTS PUBLIC.DOCUMENT_FEEDBACK (
    FEEDBACK_ID VARCHAR(128) DEFAULT UUID_STRING() PRIMARY KEY,
    DOCUMENT_ID VARCHAR(128) NOT NULL,
    USER_ID VARCHAR(128) NOT NULL,
    RATING VARCHAR(8) NOT NULL, -- 'up' | 'down'
    REASON VARCHAR(64),
    REASON_TEXT TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT UQ_DOCUMENT_FEEDBACK_USER UNIQUE (USER_ID, DOCUMENT_ID),
    CONSTRAINT FK_DOCUMENT_FEEDBACK FOREIGN KEY (DOCUMENT_ID)
        REFERENCES PUBLIC.DOCUMENTS(DOCUMENT_ID)
);

-- Weighted view for relevance ranking (decay + feedback)
CREATE OR REPLACE VIEW PUBLIC.DOCUMENTS_WEIGHTED AS
SELECT
    d.*,
    COALESCE(d.BASE_WEIGHT, 1.0) *
    EXP(-(COALESCE(d.DECAY_LAMBDA, 0.05) *
    (DATEDIFF('day', d.UPLOADED_AT, CURRENT_TIMESTAMP())) / 365.0)) *
    COALESCE(d.FEEDBACK_MULTIPLIER, 1.0) AS COMPUTED_WEIGHT
FROM PUBLIC.DOCUMENTS d
WHERE d.STATUS = 'indexed';

-- Vector index for fast similarity search
CREATE VECTOR INDEX IF NOT EXISTS IDX_DOCUMENT_CHUNKS_EMBEDDING
  ON PUBLIC.DOCUMENT_CHUNKS(EMBEDDING)
  DISTANCE_METRIC = 'COSINE';

-- Grant permissions to app service role
GRANT SELECT, INSERT, UPDATE ON PUBLIC.DOCUMENTS TO SRI_APP_SERVICE;
GRANT SELECT, INSERT, UPDATE ON PUBLIC.DOCUMENT_CHUNKS TO SRI_APP_SERVICE;
GRANT SELECT, INSERT ON PUBLIC.RETRIEVAL_VALIDATIONS TO SRI_APP_SERVICE;
GRANT SELECT, INSERT ON PUBLIC.DOCUMENT_FEEDBACK TO SRI_APP_SERVICE;
GRANT SELECT ON PUBLIC.DOCUMENTS_WEIGHTED TO SRI_APP_SERVICE;
